#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-only

"""Conservatively normalize source license headers across the ISASS workspace.

The default mode is a read-only dry run.  The normalizer intentionally skips
anything whose legal provenance is not clear enough to change safely.
"""

from __future__ import annotations

import argparse
import difflib
import fnmatch
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Iterable, Sequence


UTF8_BOM = b"\xef\xbb\xbf"
MAX_PREAMBLE_LINES = 200
MAX_PREAMBLE_BYTES = 128 * 1024

GLOBAL_EXCLUDED_PARTS = frozenset(
    {
        ".git",
        ".idea",
        ".vscode",
        ".codegraph",
        ".codex",
        "node_modules",
        "target",
        "build",
        "dist",
        "out",
        "coverage",
        "vendor",
        "third_party",
        "third-party",
        "generated",
        "logs",
    }
)

SPECIAL_FILENAMES = frozenset(
    {
        "license",
        "license.txt",
        "copying",
        "copying.lesser",
        "notice",
        "readme",
        "readme.md",
        "changelog",
        "changelog.md",
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "pom.xml",
    }
)

LINE_COMMENT_EXTENSIONS = {
    ".java": "//",
    ".kt": "//",
    ".kts": "//",
    ".groovy": "//",
    ".js": "//",
    ".mjs": "//",
    ".cjs": "//",
    ".jsx": "//",
    ".ts": "//",
    ".tsx": "//",
    ".c": "//",
    ".h": "//",
    ".cc": "//",
    ".cpp": "//",
    ".hpp": "//",
    ".go": "//",
    ".rs": "//",
    ".proto": "//",
    ".gradle": "//",
    ".py": "#",
    ".sh": "#",
    ".bash": "#",
    ".zsh": "#",
    ".yaml": "#",
    ".yml": "#",
    ".properties": "#",
    ".sql": "--",
}

BLOCK_COMMENT_EXTENSIONS = {
    ".css": ("/*", "*/"),
    ".scss": ("/*", "*/"),
    ".less": ("/*", "*/"),
}

XML_COMMENT_EXTENSIONS = frozenset({".xml", ".html", ".htm", ".vue"})
SUPPORTED_EXTENSIONS = frozenset(
    set(LINE_COMMENT_EXTENSIONS)
    | set(BLOCK_COMMENT_EXTENSIONS)
    | set(XML_COMMENT_EXTENSIONS)
    | {".ftl"}
)

GENERATED_MARKERS = (
    "generated file",
    "do not edit",
    "auto-generated",
    "automatically generated",
    "code generated",
    "generated by the protocol buffer compiler",
)

OTHER_LICENSE_MARKERS = (
    "licensed under",
    "apache license",
    "gnu general public license",
    "gnu lesser general public license",
    "mit license",
    "mozilla public license",
    "all rights reserved",
)

LGPL_REQUIRED_ANCHORS = (
    "gnu lesser general public license",
    "version 3, 29 june 2007",
    "free software foundation",
    "incorporates the terms and conditions of version 3 of the gnu general public license",
    "0. additional definitions",
    "4. combined works",
    "6. revised versions of the gnu lesser general public license",
    "proxy's public statement of acceptance",
)

APACHE_REQUIRED_ANCHORS = (
    "licensed under the apache license, version 2.0",
    "http://www.apache.org/licenses/license-2.0",
    "unless required by applicable law or agreed to in writing",
    "limitations under the license",
)


@dataclass(frozen=True)
class ProjectConfig:
    name: str
    root: Path
    spdx: str
    include_globs: tuple[str, ...]
    exclude_globs: tuple[str, ...] = ()
    copyright_holders: tuple[str, ...] = ()


@dataclass(frozen=True)
class CommentSpan:
    start: int
    end: int
    text: str


@dataclass
class Result:
    project: str
    path: Path
    classification: str
    action: str
    reason: str = ""
    original: bytes | None = field(default=None, repr=False)
    normalized: bytes | None = field(default=None, repr=False)

    def as_json(self, root: Path) -> dict[str, str]:
        try:
            relative = self.path.relative_to(root).as_posix()
        except ValueError:
            relative = str(self.path)
        return {
            "project": self.project,
            "file": relative,
            "classification": self.classification,
            "action": self.action,
            "reason": self.reason,
        }


def workspace_projects() -> dict[str, ProjectConfig]:
    framework_root = Path(__file__).resolve().parents[1]
    isass_root = framework_root.parent
    company_root = isass_root.parent
    return {
        "bsp-web-vue": ProjectConfig(
            "bsp-web-vue",
            isass_root / "bsp-web-vue",
            "Apache-2.0",
            ("src", "e2e"),
        ),
        "isass-framework-v4": ProjectConfig(
            "isass-framework-v4",
            framework_root,
            "LGPL-3.0-only",
            ("*/src",),
        ),
        "isass-service-apidoc": ProjectConfig(
            "isass-service-apidoc",
            isass_root / "isass-service-apidoc",
            "LGPL-3.0-only",
            ("*/src",),
            (
                "apidoc-openapi3/frontend/**",
                "apidoc-openapi3/src/main/resources/META-INF/resources/**",
            ),
        ),
        "isass-service-bsp": ProjectConfig(
            "isass-service-bsp",
            isass_root / "isass-service-bsp",
            "LGPL-3.0-only",
            ("*/src",),
        ),
        "iimage-asset-h5": ProjectConfig(
            "iimage-asset-h5",
            company_root / "iphoto" / "iimage-asset-h5",
            "LGPL-3.0-only",
            ("src", "tests"),
        ),
        "iimage-service-asset": ProjectConfig(
            "iimage-service-asset",
            company_root / "iphoto" / "iimage-service-asset",
            "LGPL-3.0-only",
            ("*/src", "openclaw-plugins/*/src"),
        ),
    }


def newline_for(text: str) -> str:
    match = re.search(r"\r\n|\n|\r", text)
    return match.group(0) if match else "\n"


def preamble_end(text: str) -> int:
    end = min(len(text), MAX_PREAMBLE_BYTES)
    matches = list(re.finditer(r"\r\n|\n|\r", text[:end]))
    if len(matches) >= MAX_PREAMBLE_LINES:
        return matches[MAX_PREAMBLE_LINES - 1].end()
    return end


def lines_with_offsets(text: str) -> list[tuple[int, int, str]]:
    result: list[tuple[int, int, str]] = []
    offset = 0
    for line in text.splitlines(keepends=True):
        result.append((offset, offset + len(line), line))
        offset += len(line)
    if offset < len(text):
        result.append((offset, len(text), text[offset:]))
    return result


def comment_spans(text: str, extension: str) -> list[CommentSpan]:
    head = text[:preamble_end(text)]
    spans: list[CommentSpan] = []

    if extension in XML_COMMENT_EXTENSIONS:
        for match in re.finditer(r"<!--.*?-->", head, re.DOTALL):
            spans.append(CommentSpan(match.start(), match.end(), match.group(0)))
    else:
        for match in re.finditer(r"/\*.*?\*/", head, re.DOTALL):
            spans.append(CommentSpan(match.start(), match.end(), match.group(0)))

    marker = LINE_COMMENT_EXTENSIONS.get(extension)
    if marker:
        lines = lines_with_offsets(head)
        index = 0
        while index < len(lines):
            start, end, line = lines[index]
            stripped = line.lstrip()
            is_comment = stripped.startswith(marker)
            if marker == "#" and stripped.startswith("#!"):
                is_comment = False
            if not is_comment:
                index += 1
                continue
            group_start = start
            group_end = end
            first_content = stripped[len(marker) :].lstrip()
            nested_block = first_content.startswith("/*")
            first_lower = first_content.lower()
            saw_lgpl = "gnu lesser general public license" in first_lower
            saw_lgpl_proxy = "proxy's public statement of acceptance" in first_lower
            saw_apache = "licensed under the apache license" in first_lower
            index += 1
            if nested_block and first_content.rstrip().endswith("*/"):
                spans.append(CommentSpan(group_start, group_end, head[group_start:group_end]))
                continue
            while index < len(lines):
                next_start, next_end, next_line = lines[index]
                next_stripped = next_line.lstrip()
                if next_stripped.startswith(marker) and not (
                    marker == "#" and next_stripped.startswith("#!")
                ):
                    group_end = next_end
                    index += 1
                    nested_content = next_stripped[len(marker) :].lstrip()
                    nested_lower = nested_content.lower()
                    saw_lgpl = saw_lgpl or "gnu lesser general public license" in nested_lower
                    saw_lgpl_proxy = saw_lgpl_proxy or "proxy's public statement of acceptance" in nested_lower
                    saw_apache = saw_apache or "licensed under the apache license" in nested_lower
                    if nested_block and nested_content.rstrip().endswith("*/"):
                        break
                    semantic_line = re.sub(r"^\s*(?:\*|~)\s?", "", nested_content).strip().lower()
                    if not nested_block and saw_lgpl and saw_lgpl_proxy and semantic_line.endswith("library."):
                        break
                    if not nested_block and saw_apache and semantic_line.endswith("limitations under the license."):
                        break
                    continue
                if not next_stripped.strip() and index + 1 < len(lines):
                    following = lines[index + 1][2].lstrip()
                    if following.startswith(marker) and not (
                        marker == "#" and following.startswith("#!")
                    ):
                        group_end = next_end
                        index += 1
                        continue
                break
            spans.append(CommentSpan(group_start, group_end, head[group_start:group_end]))

    spans.sort(key=lambda item: (item.start, item.end))
    deduplicated: list[CommentSpan] = []
    for span in spans:
        if deduplicated and span.start >= deduplicated[-1].start and span.end <= deduplicated[-1].end:
            continue
        deduplicated.append(span)
    return deduplicated


def semantic_comment_text(value: str) -> str:
    line_unwrapped: list[str] = []
    for line in value.splitlines():
        line_unwrapped.append(re.sub(r"^\s*(?://|#|--)\s?", "", line).rstrip())
    value = "\n".join(line_unwrapped)
    value = re.sub(r"^\s*/\*+", "", value)
    value = re.sub(r"\*/\s*$", "", value)
    value = re.sub(r"^\s*<!--", "", value)
    value = re.sub(r"-->\s*$", "", value)
    cleaned: list[str] = []
    for line in value.splitlines():
        line = re.sub(r"^\s*(?:\*|~)\s?", "", line)
        cleaned.append(line.rstrip())
    return "\n".join(cleaned).strip()


def spdx_values(spans: Sequence[CommentSpan]) -> list[tuple[CommentSpan, str]]:
    values: list[tuple[CommentSpan, str]] = []
    for span in spans:
        semantic = semantic_comment_text(span.text)
        for match in re.finditer(r"(?im)^SPDX-License-Identifier:\s*(.+?)\s*$", semantic):
            values.append((span, match.group(1).strip()))
    return values


def copyright_lines(span: CommentSpan) -> list[str]:
    return [
        line.strip()
        for line in semantic_comment_text(span.text).splitlines()
        if re.match(r"(?i)^(?:copyright(?:\s|\s*[(:])|\(c\)\s*\d)", line.strip())
    ]


def known_verbose_license(span: CommentSpan, config: ProjectConfig) -> str | None:
    semantic = semantic_comment_text(span.text)
    normalized = " ".join(semantic.lower().split())
    if all(anchor in normalized for anchor in LGPL_REQUIRED_ANCHORS):
        copyrights = copyright_lines(span)
        if copyrights and all("free software foundation" in line.lower() for line in copyrights):
            return "LGPL-3.0-only"
    if all(anchor in normalized for anchor in APACHE_REQUIRED_ANCHORS):
        copyrights = copyright_lines(span)
        if not copyrights:
            return "Apache-2.0"
        holders = tuple(holder.casefold() for holder in config.copyright_holders)
        if holders and all(any(holder in line.casefold() for holder in holders) for line in copyrights):
            return "Apache-2.0"
    return None


def has_legal_marker(spans: Sequence[CommentSpan]) -> bool:
    for span in spans:
        semantic = semantic_comment_text(span.text).lower()
        if "copyright" in semantic or any(marker in semantic for marker in OTHER_LICENSE_MARKERS):
            return True
    return False


def is_only_spdx(span: CommentSpan, expected: str) -> bool:
    lines = [line.strip() for line in semantic_comment_text(span.text).splitlines() if line.strip()]
    return lines == [f"SPDX-License-Identifier: {expected}"]


def special_prefix_end(text: str, extension: str) -> int:
    lines = lines_with_offsets(text)
    index = 0
    end = 0
    if lines and text.startswith("#!") and extension in {".py", ".sh", ".bash", ".zsh"}:
        end = lines[0][1]
        index = 1
    if extension == ".py":
        for candidate in range(index, min(index + 2, len(lines))):
            if re.match(r"^[ \t]*#.*coding[:=][ \t]*[-\w.]+", lines[candidate][2]):
                end = lines[candidate][1]
                index = candidate + 1
    if extension in XML_COMMENT_EXTENSIONS and lines:
        match = re.match(r"\s*<\?xml\b.*?\?>", text, re.DOTALL)
        if match:
            end = match.end()
            newline = re.match(r"\r\n|\n|\r", text[end:])
            if newline:
                end += newline.end()
    return end


def rendered_header(extension: str, spdx: str, newline: str) -> str:
    value = f"SPDX-License-Identifier: {spdx}"
    if extension in XML_COMMENT_EXTENSIONS:
        return f"<!-- {value} -->"
    if extension in BLOCK_COMMENT_EXTENSIONS:
        return f"/* {value} */"
    marker = LINE_COMMENT_EXTENSIONS[extension]
    return f"{marker} {value}"


def insert_header(text: str, extension: str, spdx: str) -> str:
    newline = newline_for(text)
    prefix_end = special_prefix_end(text, extension)
    suffix_start = prefix_end
    while suffix_start < len(text) and text[suffix_start] in " \t\r\n":
        suffix_start += 1
    prefix = text[:prefix_end]
    suffix = text[suffix_start:]
    separator = newline if prefix else ""
    trailing = newline * 2 if suffix else newline
    return prefix + separator + rendered_header(extension, spdx, newline) + trailing + suffix


def normalize_span(text: str, extension: str, spdx: str, span: CommentSpan) -> str:
    without = text[: span.start] + text[span.end :]
    return insert_header(without, extension, spdx)


def extend_over_trailing_blank_comments(text: str, extension: str, span: CommentSpan) -> CommentSpan:
    marker = LINE_COMMENT_EXTENSIONS.get(extension)
    if not marker:
        return span
    end = span.end
    for start, line_end, line in lines_with_offsets(text[end:]):
        stripped = line.strip()
        if not stripped or stripped == marker:
            end = span.end + line_end
            continue
        break
    return CommentSpan(span.start, end, text[span.start:end])


def generated_preamble(text: str, spans: Sequence[CommentSpan]) -> bool:
    semantic = "\n".join(semantic_comment_text(span.text).lower() for span in spans)
    return any(marker in semantic for marker in GENERATED_MARKERS)


def minified(path: Path, text: str) -> bool:
    lower = path.name.lower()
    if lower.endswith(".min.js") or lower.endswith(".min.css") or lower in {"bundle.js", "vendor.js"}:
        return True
    head = text[:MAX_PREAMBLE_BYTES]
    return any(len(line) > 5000 for line in head.splitlines())


def encode_like(original: bytes, text: str) -> bytes:
    bom = UTF8_BOM if original.startswith(UTF8_BOM) else b""
    return bom + text.encode("utf-8")


def effective_extension(path: Path) -> str:
    if path.name.endswith(".xml.ftl"):
        return ".xml"
    if path.suffix.lower() == ".ftl":
        return ".java"
    return path.suffix.lower()


def classify_file(path: Path, config: ProjectConfig) -> Result:
    try:
        original = path.read_bytes()
    except OSError as error:
        return Result(config.name, path, "ERROR", "ERROR", str(error))
    if not original:
        return Result(config.name, path, "EMPTY", "SKIP", "empty file")
    if b"\0" in original[:8192]:
        return Result(config.name, path, "UNSUPPORTED", "SKIP", "binary data")

    payload = original[len(UTF8_BOM) :] if original.startswith(UTF8_BOM) else original
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as error:
        return Result(config.name, path, "UNSUPPORTED", "ERROR", f"not UTF-8: {error}")
    if not text.strip():
        return Result(config.name, path, "EMPTY", "SKIP", "whitespace-only file")

    source_extension = path.suffix.lower()
    if source_extension not in SUPPORTED_EXTENSIONS:
        return Result(config.name, path, "UNSUPPORTED", "SKIP", f"unsupported extension {source_extension}")
    extension = effective_extension(path)

    spans = comment_spans(text, extension)
    if generated_preamble(text, spans):
        return Result(config.name, path, "GENERATED", "SKIP", "generated-file marker")
    if minified(path, text):
        return Result(config.name, path, "MINIFIED", "SKIP", "minified or bundled file")

    spdx = spdx_values(spans)
    if len(spdx) > 1:
        values = ", ".join(value for _, value in spdx)
        return Result(config.name, path, "AMBIGUOUS", "WARN", f"multiple SPDX declarations: {values}")
    if spdx:
        span, value = spdx[0]
        if value != config.spdx:
            return Result(
                config.name,
                path,
                "OTHER_LICENSE",
                "WARN",
                f"existing SPDX {value} differs from expected {config.spdx}",
            )
        if not is_only_spdx(span, config.spdx):
            return Result(
                config.name,
                path,
                "TARGET_SHORT_LICENSE",
                "OK",
                "target SPDX shares a comment with preserved attribution",
            )
        normalized_text = normalize_span(text, extension, config.spdx, span)
        normalized = encode_like(original, normalized_text)
        if normalized == original:
            return Result(config.name, path, "TARGET_SHORT_LICENSE", "OK")
        return Result(
            config.name,
            path,
            "TARGET_LICENSE_MISPLACED",
            "RELOCATE",
            "move target SPDX to the language-safe preamble",
            original,
            normalized,
        )

    verbose = [(span, known_verbose_license(span, config)) for span in spans]
    verbose = [(span, license_id) for span, license_id in verbose if license_id]
    if len(verbose) > 1:
        return Result(config.name, path, "AMBIGUOUS", "WARN", "multiple recognized license blocks")
    if verbose:
        span, license_id = verbose[0]
        if license_id != config.spdx:
            return Result(
                config.name,
                path,
                "OTHER_LICENSE",
                "WARN",
                f"recognized {license_id} header differs from expected {config.spdx}",
            )
        other_legal = [candidate for candidate in spans if candidate != span and has_legal_marker([candidate])]
        if other_legal:
            return Result(
                config.name,
                path,
                "MULTIPLE_COPYRIGHT",
                "SKIP",
                "additional legal or copyright comment must be preserved",
            )
        span = extend_over_trailing_blank_comments(text, extension, span)
        normalized_text = normalize_span(text, extension, config.spdx, span)
        normalized = encode_like(original, normalized_text)
        action = "REPLACE" if span.start <= special_prefix_end(text, extension) + len(newline_for(text)) else "RELOCATE"
        return Result(
            config.name,
            path,
            "TARGET_VERBOSE_LICENSE" if action == "REPLACE" else "TARGET_LICENSE_MISPLACED",
            action,
            "replace recognized project-standard verbose license with SPDX",
            original,
            normalized,
        )

    if has_legal_marker(spans):
        copyrights = [line for span in spans for line in copyright_lines(span)]
        if len(copyrights) > 1:
            return Result(
                config.name,
                path,
                "MULTIPLE_COPYRIGHT",
                "SKIP",
                "multiple copyright statements preserved unchanged",
            )
        copyright_found = bool(copyrights)
        classification = "THIRD_PARTY_LICENSE" if copyright_found else "OTHER_LICENSE"
        return Result(
            config.name,
            path,
            classification,
            "SKIP" if copyright_found else "WARN",
            "unrecognized legal metadata preserved unchanged",
        )

    normalized_text = insert_header(text, extension, config.spdx)
    normalized = encode_like(original, normalized_text)
    return Result(
        config.name,
        path,
        "NO_LICENSE",
        "ADD",
        f"add SPDX {config.spdx}",
        original,
        normalized,
    )


def matches_any(path: PurePosixPath, patterns: Sequence[str]) -> bool:
    value = path.as_posix()
    return any(fnmatch.fnmatch(value, pattern) for pattern in patterns)


def excluded(path: Path, config: ProjectConfig, extra_excludes: Sequence[str]) -> bool:
    relative = PurePosixPath(path.relative_to(config.root).as_posix())
    if any(part in GLOBAL_EXCLUDED_PARTS for part in relative.parts):
        return True
    if matches_any(relative, (*config.exclude_globs, *extra_excludes)):
        return True
    lower = path.name.lower()
    return lower.endswith(".min.js") or lower.endswith(".min.css") or lower in {"bundle.js", "vendor.js"}


def walk_candidate(candidate: Path) -> Iterable[Path]:
    if candidate.is_file():
        yield candidate
    elif candidate.is_dir():
        yield from candidate.rglob("*")


def discover_files(
    config: ProjectConfig,
    explicit_paths: Sequence[str],
    include_globs: Sequence[str],
    exclude_globs: Sequence[str],
) -> list[Path]:
    candidates: list[tuple[Path, bool]] = []
    if explicit_paths:
        for value in explicit_paths:
            candidate = (config.root / value).resolve() if not Path(value).is_absolute() else Path(value).resolve()
            try:
                candidate.relative_to(config.root.resolve())
            except ValueError as error:
                raise ValueError(f"path is outside project root: {candidate}") from error
            candidates.append((candidate, True))
    else:
        patterns = tuple(include_globs) if include_globs else config.include_globs
        for pattern in patterns:
            candidates.extend((candidate, False) for candidate in config.root.glob(pattern))

    files: set[Path] = set()
    for candidate, explicit in candidates:
        if not candidate.exists():
            raise ValueError(f"path does not exist: {candidate}")
        for path in walk_candidate(candidate):
            if not path.is_file() or excluded(path, config, exclude_globs):
                continue
            if path.suffix.lower() not in SUPPORTED_EXTENSIONS:
                continue
            if not explicit and path.suffix.lower() == ".ftl":
                continue
            if not explicit and path.name.lower() in SPECIAL_FILENAMES:
                continue
            files.add(path)
    return sorted(files)


def print_result(result: Result, root: Path, verbose: bool) -> None:
    relative = result.path.relative_to(root)
    if result.action == "OK" and not verbose:
        return
    detail = f" - {result.reason}" if result.reason else ""
    print(f"[{result.action:<8}] {relative}{detail}")


def print_diff(result: Result, root: Path) -> None:
    if result.original is None or result.normalized is None:
        return
    before = result.original.decode("utf-8-sig").splitlines(keepends=True)
    after = result.normalized.decode("utf-8-sig").splitlines(keepends=True)
    relative = result.path.relative_to(root).as_posix()
    sys.stdout.writelines(
        difflib.unified_diff(before, after, fromfile=f"a/{relative}", tofile=f"b/{relative}")
    )


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    projects = workspace_projects()
    result.add_argument("paths", nargs="*", help="files or directories relative to the selected project")
    result.add_argument("--project", choices=tuple(projects), default="isass-framework-v4")
    result.add_argument("--all-projects", action="store_true", help="scan all configured workspace projects")
    mode = result.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true", help="show changes without writing (default)")
    mode.add_argument("--apply", action="store_true", help="write safe planned changes")
    mode.add_argument("--check", action="store_true", help="exit non-zero when normalization is needed")
    result.add_argument("--include", action="append", default=[], help="override default include glob")
    result.add_argument("--exclude", action="append", default=[], help="add an exclude glob")
    result.add_argument("--show-diff", action="store_true")
    result.add_argument("--verbose", action="store_true")
    result.add_argument("--report", type=Path, help="write a JSON classification report")
    return result


def main(argv: Sequence[str] | None = None) -> int:
    args = parser().parse_args(argv)
    if args.all_projects and args.paths:
        parser().error("explicit paths cannot be combined with --all-projects")
    if args.all_projects and args.include:
        parser().error("--include cannot be combined with --all-projects")

    configured = workspace_projects()
    selected = list(configured.values()) if args.all_projects else [configured[args.project]]
    all_results: list[tuple[ProjectConfig, Result]] = []
    errors = False
    planned = False

    for config in selected:
        if not config.root.is_dir():
            print(f"[ERROR   ] {config.name} - project root does not exist: {config.root}", file=sys.stderr)
            errors = True
            continue
        try:
            files = discover_files(config, args.paths, args.include, args.exclude)
        except ValueError as error:
            print(f"[ERROR   ] {config.name} - {error}", file=sys.stderr)
            errors = True
            continue
        print(f"\n== {config.name} ({config.spdx}) ==")
        results = [classify_file(path, config) for path in files]
        for result in results:
            print_result(result, config.root, args.verbose)
            if args.show_diff and result.action in {"ADD", "REPLACE", "RELOCATE"}:
                print_diff(result, config.root)
            if result.action in {"ADD", "REPLACE", "RELOCATE"}:
                planned = True
                if args.apply and result.normalized is not None:
                    result.path.write_bytes(result.normalized)
            if result.action == "ERROR":
                errors = True
            all_results.append((config, result))
        counts = Counter(result.action for result in results)
        print(
            "Scanned: {scanned}  OK: {ok}  Add: {add}  Replace: {replace}  "
            "Relocate: {relocate}  Skip: {skip}  Warn: {warn}  Error: {error}".format(
                scanned=len(results),
                ok=counts["OK"],
                add=counts["ADD"],
                replace=counts["REPLACE"],
                relocate=counts["RELOCATE"],
                skip=counts["SKIP"],
                warn=counts["WARN"],
                error=counts["ERROR"],
            )
        )

    if args.report:
        payload = [result.as_json(config.root) for config, result in all_results]
        args.report.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if errors:
        return 2
    if args.check and planned:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
