// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NetworkFrame.proto
// Protobuf Java Version: 4.33.0

package vip.isass.framework.net.netty.protobuf.base;

@com.google.protobuf.Generated
public final class NetworkFrame extends com.google.protobuf.GeneratedFile {
  private NetworkFrame() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "NetworkFrame");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HttpFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Platform.Model.HttpFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     *
     * <code>optional int64 c2sId = 1;</code>
     * @return Whether the c2sId field is set.
     */
    boolean hasC2SId();
    /**
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     *
     * <code>optional int64 c2sId = 1;</code>
     * @return The c2sId.
     */
    long getC2SId();

    /**
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     *
     * <code>optional int64 s2cId = 2;</code>
     * @return Whether the s2cId field is set.
     */
    boolean hasS2CId();
    /**
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     *
     * <code>optional int64 s2cId = 2;</code>
     * @return The s2cId.
     */
    long getS2CId();

    /**
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassC2S = 3;</code>
     * @return Whether the javaProtobufClassC2S field is set.
     */
    boolean hasJavaProtobufClassC2S();
    /**
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassC2S = 3;</code>
     * @return The javaProtobufClassC2S.
     */
    java.lang.String getJavaProtobufClassC2S();
    /**
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassC2S = 3;</code>
     * @return The bytes for javaProtobufClassC2S.
     */
    com.google.protobuf.ByteString
        getJavaProtobufClassC2SBytes();

    /**
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassS2C = 4;</code>
     * @return Whether the javaProtobufClassS2C field is set.
     */
    boolean hasJavaProtobufClassS2C();
    /**
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassS2C = 4;</code>
     * @return The javaProtobufClassS2C.
     */
    java.lang.String getJavaProtobufClassS2C();
    /**
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassS2C = 4;</code>
     * @return The bytes for javaProtobufClassS2C.
     */
    com.google.protobuf.ByteString
        getJavaProtobufClassS2CBytes();

    /**
     * <pre>
     * 请求url
     * </pre>
     *
     * <code>optional string url = 5;</code>
     * @return Whether the url field is set.
     */
    boolean hasUrl();
    /**
     * <pre>
     * 请求url
     * </pre>
     *
     * <code>optional string url = 5;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <pre>
     * 请求url
     * </pre>
     *
     * <code>optional string url = 5;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     * http 请求方法
     * </pre>
     *
     * <code>optional int32 httpMethod = 6;</code>
     * @return Whether the httpMethod field is set.
     */
    boolean hasHttpMethod();
    /**
     * <pre>
     * http 请求方法
     * </pre>
     *
     * <code>optional int32 httpMethod = 6;</code>
     * @return The httpMethod.
     */
    int getHttpMethod();

    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    java.util.List<vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry> 
        getHttpHeadersList();
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry getHttpHeaders(int index);
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    int getHttpHeadersCount();
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    java.util.List<? extends vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder> 
        getHttpHeadersOrBuilderList();
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder getHttpHeadersOrBuilder(
        int index);

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional bytes body = 8;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional bytes body = 8;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code Platform.Model.HttpFrame}
   */
  public static final class HttpFrame extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Platform.Model.HttpFrame)
      HttpFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "HttpFrame");
    }
    // Use HttpFrame.newBuilder() to construct.
    private HttpFrame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HttpFrame() {
      javaProtobufClassC2S_ = "";
      javaProtobufClassS2C_ = "";
      url_ = "";
      httpHeaders_ = java.util.Collections.emptyList();
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_HttpFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_HttpFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame.class, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame.Builder.class);
    }

    private int bitField0_;
    public static final int C2SID_FIELD_NUMBER = 1;
    private long c2SId_ = 0L;
    /**
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     *
     * <code>optional int64 c2sId = 1;</code>
     * @return Whether the c2sId field is set.
     */
    @java.lang.Override
    public boolean hasC2SId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     *
     * <code>optional int64 c2sId = 1;</code>
     * @return The c2sId.
     */
    @java.lang.Override
    public long getC2SId() {
      return c2SId_;
    }

    public static final int S2CID_FIELD_NUMBER = 2;
    private long s2CId_ = 0L;
    /**
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     *
     * <code>optional int64 s2cId = 2;</code>
     * @return Whether the s2cId field is set.
     */
    @java.lang.Override
    public boolean hasS2CId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     *
     * <code>optional int64 s2cId = 2;</code>
     * @return The s2cId.
     */
    @java.lang.Override
    public long getS2CId() {
      return s2CId_;
    }

    public static final int JAVAPROTOBUFCLASSC2S_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object javaProtobufClassC2S_ = "";
    /**
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassC2S = 3;</code>
     * @return Whether the javaProtobufClassC2S field is set.
     */
    @java.lang.Override
    public boolean hasJavaProtobufClassC2S() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassC2S = 3;</code>
     * @return The javaProtobufClassC2S.
     */
    @java.lang.Override
    public java.lang.String getJavaProtobufClassC2S() {
      java.lang.Object ref = javaProtobufClassC2S_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          javaProtobufClassC2S_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassC2S = 3;</code>
     * @return The bytes for javaProtobufClassC2S.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJavaProtobufClassC2SBytes() {
      java.lang.Object ref = javaProtobufClassC2S_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaProtobufClassC2S_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JAVAPROTOBUFCLASSS2C_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object javaProtobufClassS2C_ = "";
    /**
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassS2C = 4;</code>
     * @return Whether the javaProtobufClassS2C field is set.
     */
    @java.lang.Override
    public boolean hasJavaProtobufClassS2C() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassS2C = 4;</code>
     * @return The javaProtobufClassS2C.
     */
    @java.lang.Override
    public java.lang.String getJavaProtobufClassS2C() {
      java.lang.Object ref = javaProtobufClassS2C_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          javaProtobufClassS2C_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     *
     * <code>optional string javaProtobufClassS2C = 4;</code>
     * @return The bytes for javaProtobufClassS2C.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJavaProtobufClassS2CBytes() {
      java.lang.Object ref = javaProtobufClassS2C_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaProtobufClassS2C_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object url_ = "";
    /**
     * <pre>
     * 请求url
     * </pre>
     *
     * <code>optional string url = 5;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 请求url
     * </pre>
     *
     * <code>optional string url = 5;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 请求url
     * </pre>
     *
     * <code>optional string url = 5;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTTPMETHOD_FIELD_NUMBER = 6;
    private int httpMethod_ = 0;
    /**
     * <pre>
     * http 请求方法
     * </pre>
     *
     * <code>optional int32 httpMethod = 6;</code>
     * @return Whether the httpMethod field is set.
     */
    @java.lang.Override
    public boolean hasHttpMethod() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * http 请求方法
     * </pre>
     *
     * <code>optional int32 httpMethod = 6;</code>
     * @return The httpMethod.
     */
    @java.lang.Override
    public int getHttpMethod() {
      return httpMethod_;
    }

    public static final int HTTPHEADERS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private java.util.List<vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry> httpHeaders_;
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    @java.lang.Override
    public java.util.List<vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry> getHttpHeadersList() {
      return httpHeaders_;
    }
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    @java.lang.Override
    public java.util.List<? extends vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder> 
        getHttpHeadersOrBuilderList() {
      return httpHeaders_;
    }
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    @java.lang.Override
    public int getHttpHeadersCount() {
      return httpHeaders_.size();
    }
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    @java.lang.Override
    public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry getHttpHeaders(int index) {
      return httpHeaders_.get(index);
    }
    /**
     * <pre>
     * http 请求头
     * </pre>
     *
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     */
    @java.lang.Override
    public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder getHttpHeadersOrBuilder(
        int index) {
      return httpHeaders_.get(index);
    }

    public static final int BODY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional bytes body = 8;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional bytes body = 8;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getHttpHeadersCount(); i++) {
        if (!getHttpHeaders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, c2SId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, s2CId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, javaProtobufClassC2S_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, javaProtobufClassS2C_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, url_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, httpMethod_);
      }
      for (int i = 0; i < httpHeaders_.size(); i++) {
        output.writeMessage(7, httpHeaders_.get(i));
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBytes(8, body_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, c2SId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, s2CId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, javaProtobufClassC2S_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, javaProtobufClassS2C_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, url_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, httpMethod_);
      }
      for (int i = 0; i < httpHeaders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, httpHeaders_.get(i));
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame)) {
        return super.equals(obj);
      }
      vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame other = (vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame) obj;

      if (hasC2SId() != other.hasC2SId()) return false;
      if (hasC2SId()) {
        if (getC2SId()
            != other.getC2SId()) return false;
      }
      if (hasS2CId() != other.hasS2CId()) return false;
      if (hasS2CId()) {
        if (getS2CId()
            != other.getS2CId()) return false;
      }
      if (hasJavaProtobufClassC2S() != other.hasJavaProtobufClassC2S()) return false;
      if (hasJavaProtobufClassC2S()) {
        if (!getJavaProtobufClassC2S()
            .equals(other.getJavaProtobufClassC2S())) return false;
      }
      if (hasJavaProtobufClassS2C() != other.hasJavaProtobufClassS2C()) return false;
      if (hasJavaProtobufClassS2C()) {
        if (!getJavaProtobufClassS2C()
            .equals(other.getJavaProtobufClassS2C())) return false;
      }
      if (hasUrl() != other.hasUrl()) return false;
      if (hasUrl()) {
        if (!getUrl()
            .equals(other.getUrl())) return false;
      }
      if (hasHttpMethod() != other.hasHttpMethod()) return false;
      if (hasHttpMethod()) {
        if (getHttpMethod()
            != other.getHttpMethod()) return false;
      }
      if (!getHttpHeadersList()
          .equals(other.getHttpHeadersList())) return false;
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasC2SId()) {
        hash = (37 * hash) + C2SID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getC2SId());
      }
      if (hasS2CId()) {
        hash = (37 * hash) + S2CID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getS2CId());
      }
      if (hasJavaProtobufClassC2S()) {
        hash = (37 * hash) + JAVAPROTOBUFCLASSC2S_FIELD_NUMBER;
        hash = (53 * hash) + getJavaProtobufClassC2S().hashCode();
      }
      if (hasJavaProtobufClassS2C()) {
        hash = (37 * hash) + JAVAPROTOBUFCLASSS2C_FIELD_NUMBER;
        hash = (53 * hash) + getJavaProtobufClassS2C().hashCode();
      }
      if (hasUrl()) {
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
      }
      if (hasHttpMethod()) {
        hash = (37 * hash) + HTTPMETHOD_FIELD_NUMBER;
        hash = (53 * hash) + getHttpMethod();
      }
      if (getHttpHeadersCount() > 0) {
        hash = (37 * hash) + HTTPHEADERS_FIELD_NUMBER;
        hash = (53 * hash) + getHttpHeadersList().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.Model.HttpFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Platform.Model.HttpFrame)
        vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_HttpFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_HttpFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame.class, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame.Builder.class);
      }

      // Construct using vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        c2SId_ = 0L;
        s2CId_ = 0L;
        javaProtobufClassC2S_ = "";
        javaProtobufClassS2C_ = "";
        url_ = "";
        httpMethod_ = 0;
        if (httpHeadersBuilder_ == null) {
          httpHeaders_ = java.util.Collections.emptyList();
        } else {
          httpHeaders_ = null;
          httpHeadersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        body_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_HttpFrame_descriptor;
      }

      @java.lang.Override
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame getDefaultInstanceForType() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame.getDefaultInstance();
      }

      @java.lang.Override
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame build() {
        vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame buildPartial() {
        vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame result = new vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame result) {
        if (httpHeadersBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0)) {
            httpHeaders_ = java.util.Collections.unmodifiableList(httpHeaders_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.httpHeaders_ = httpHeaders_;
        } else {
          result.httpHeaders_ = httpHeadersBuilder_.build();
        }
      }

      private void buildPartial0(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.c2SId_ = c2SId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.s2CId_ = s2CId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.javaProtobufClassC2S_ = javaProtobufClassC2S_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.javaProtobufClassS2C_ = javaProtobufClassS2C_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.url_ = url_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.httpMethod_ = httpMethod_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.body_ = body_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame) {
          return mergeFrom((vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame other) {
        if (other == vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame.getDefaultInstance()) return this;
        if (other.hasC2SId()) {
          setC2SId(other.getC2SId());
        }
        if (other.hasS2CId()) {
          setS2CId(other.getS2CId());
        }
        if (other.hasJavaProtobufClassC2S()) {
          javaProtobufClassC2S_ = other.javaProtobufClassC2S_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasJavaProtobufClassS2C()) {
          javaProtobufClassS2C_ = other.javaProtobufClassS2C_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasUrl()) {
          url_ = other.url_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasHttpMethod()) {
          setHttpMethod(other.getHttpMethod());
        }
        if (httpHeadersBuilder_ == null) {
          if (!other.httpHeaders_.isEmpty()) {
            if (httpHeaders_.isEmpty()) {
              httpHeaders_ = other.httpHeaders_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureHttpHeadersIsMutable();
              httpHeaders_.addAll(other.httpHeaders_);
            }
            onChanged();
          }
        } else {
          if (!other.httpHeaders_.isEmpty()) {
            if (httpHeadersBuilder_.isEmpty()) {
              httpHeadersBuilder_.dispose();
              httpHeadersBuilder_ = null;
              httpHeaders_ = other.httpHeaders_;
              bitField0_ = (bitField0_ & ~0x00000040);
              httpHeadersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetHttpHeadersFieldBuilder() : null;
            } else {
              httpHeadersBuilder_.addAllMessages(other.httpHeaders_);
            }
          }
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getHttpHeadersCount(); i++) {
          if (!getHttpHeaders(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                c2SId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                s2CId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                javaProtobufClassC2S_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                javaProtobufClassS2C_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                url_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                httpMethod_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry m =
                    input.readMessage(
                        vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.parser(),
                        extensionRegistry);
                if (httpHeadersBuilder_ == null) {
                  ensureHttpHeadersIsMutable();
                  httpHeaders_.add(m);
                } else {
                  httpHeadersBuilder_.addMessage(m);
                }
                break;
              } // case 58
              case 66: {
                body_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long c2SId_ ;
      /**
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       *
       * <code>optional int64 c2sId = 1;</code>
       * @return Whether the c2sId field is set.
       */
      @java.lang.Override
      public boolean hasC2SId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       *
       * <code>optional int64 c2sId = 1;</code>
       * @return The c2sId.
       */
      @java.lang.Override
      public long getC2SId() {
        return c2SId_;
      }
      /**
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       *
       * <code>optional int64 c2sId = 1;</code>
       * @param value The c2sId to set.
       * @return This builder for chaining.
       */
      public Builder setC2SId(long value) {

        c2SId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       *
       * <code>optional int64 c2sId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearC2SId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c2SId_ = 0L;
        onChanged();
        return this;
      }

      private long s2CId_ ;
      /**
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       *
       * <code>optional int64 s2cId = 2;</code>
       * @return Whether the s2cId field is set.
       */
      @java.lang.Override
      public boolean hasS2CId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       *
       * <code>optional int64 s2cId = 2;</code>
       * @return The s2cId.
       */
      @java.lang.Override
      public long getS2CId() {
        return s2CId_;
      }
      /**
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       *
       * <code>optional int64 s2cId = 2;</code>
       * @param value The s2cId to set.
       * @return This builder for chaining.
       */
      public Builder setS2CId(long value) {

        s2CId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       *
       * <code>optional int64 s2cId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearS2CId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object javaProtobufClassC2S_ = "";
      /**
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassC2S = 3;</code>
       * @return Whether the javaProtobufClassC2S field is set.
       */
      public boolean hasJavaProtobufClassC2S() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassC2S = 3;</code>
       * @return The javaProtobufClassC2S.
       */
      public java.lang.String getJavaProtobufClassC2S() {
        java.lang.Object ref = javaProtobufClassC2S_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            javaProtobufClassC2S_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassC2S = 3;</code>
       * @return The bytes for javaProtobufClassC2S.
       */
      public com.google.protobuf.ByteString
          getJavaProtobufClassC2SBytes() {
        java.lang.Object ref = javaProtobufClassC2S_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          javaProtobufClassC2S_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassC2S = 3;</code>
       * @param value The javaProtobufClassC2S to set.
       * @return This builder for chaining.
       */
      public Builder setJavaProtobufClassC2S(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        javaProtobufClassC2S_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassC2S = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaProtobufClassC2S() {
        javaProtobufClassC2S_ = getDefaultInstance().getJavaProtobufClassC2S();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassC2S = 3;</code>
       * @param value The bytes for javaProtobufClassC2S to set.
       * @return This builder for chaining.
       */
      public Builder setJavaProtobufClassC2SBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        javaProtobufClassC2S_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object javaProtobufClassS2C_ = "";
      /**
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassS2C = 4;</code>
       * @return Whether the javaProtobufClassS2C field is set.
       */
      public boolean hasJavaProtobufClassS2C() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassS2C = 4;</code>
       * @return The javaProtobufClassS2C.
       */
      public java.lang.String getJavaProtobufClassS2C() {
        java.lang.Object ref = javaProtobufClassS2C_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            javaProtobufClassS2C_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassS2C = 4;</code>
       * @return The bytes for javaProtobufClassS2C.
       */
      public com.google.protobuf.ByteString
          getJavaProtobufClassS2CBytes() {
        java.lang.Object ref = javaProtobufClassS2C_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          javaProtobufClassS2C_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassS2C = 4;</code>
       * @param value The javaProtobufClassS2C to set.
       * @return This builder for chaining.
       */
      public Builder setJavaProtobufClassS2C(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        javaProtobufClassS2C_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassS2C = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaProtobufClassS2C() {
        javaProtobufClassS2C_ = getDefaultInstance().getJavaProtobufClassS2C();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       *
       * <code>optional string javaProtobufClassS2C = 4;</code>
       * @param value The bytes for javaProtobufClassS2C to set.
       * @return This builder for chaining.
       */
      public Builder setJavaProtobufClassS2CBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        javaProtobufClassS2C_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <pre>
       * 请求url
       * </pre>
       *
       * <code>optional string url = 5;</code>
       * @return Whether the url field is set.
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 请求url
       * </pre>
       *
       * <code>optional string url = 5;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求url
       * </pre>
       *
       * <code>optional string url = 5;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求url
       * </pre>
       *
       * <code>optional string url = 5;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求url
       * </pre>
       *
       * <code>optional string url = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        url_ = getDefaultInstance().getUrl();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求url
       * </pre>
       *
       * <code>optional string url = 5;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int httpMethod_ ;
      /**
       * <pre>
       * http 请求方法
       * </pre>
       *
       * <code>optional int32 httpMethod = 6;</code>
       * @return Whether the httpMethod field is set.
       */
      @java.lang.Override
      public boolean hasHttpMethod() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * http 请求方法
       * </pre>
       *
       * <code>optional int32 httpMethod = 6;</code>
       * @return The httpMethod.
       */
      @java.lang.Override
      public int getHttpMethod() {
        return httpMethod_;
      }
      /**
       * <pre>
       * http 请求方法
       * </pre>
       *
       * <code>optional int32 httpMethod = 6;</code>
       * @param value The httpMethod to set.
       * @return This builder for chaining.
       */
      public Builder setHttpMethod(int value) {

        httpMethod_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * http 请求方法
       * </pre>
       *
       * <code>optional int32 httpMethod = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHttpMethod() {
        bitField0_ = (bitField0_ & ~0x00000020);
        httpMethod_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry> httpHeaders_ =
        java.util.Collections.emptyList();
      private void ensureHttpHeadersIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          httpHeaders_ = new java.util.ArrayList<vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry>(httpHeaders_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder> httpHeadersBuilder_;

      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public java.util.List<vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry> getHttpHeadersList() {
        if (httpHeadersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(httpHeaders_);
        } else {
          return httpHeadersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public int getHttpHeadersCount() {
        if (httpHeadersBuilder_ == null) {
          return httpHeaders_.size();
        } else {
          return httpHeadersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry getHttpHeaders(int index) {
        if (httpHeadersBuilder_ == null) {
          return httpHeaders_.get(index);
        } else {
          return httpHeadersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder setHttpHeaders(
          int index, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry value) {
        if (httpHeadersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpHeadersIsMutable();
          httpHeaders_.set(index, value);
          onChanged();
        } else {
          httpHeadersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder setHttpHeaders(
          int index, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder builderForValue) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.set(index, builderForValue.build());
          onChanged();
        } else {
          httpHeadersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder addHttpHeaders(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry value) {
        if (httpHeadersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(value);
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder addHttpHeaders(
          int index, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry value) {
        if (httpHeadersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(index, value);
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder addHttpHeaders(
          vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder builderForValue) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(builderForValue.build());
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder addHttpHeaders(
          int index, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder builderForValue) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(index, builderForValue.build());
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder addAllHttpHeaders(
          java.lang.Iterable<? extends vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry> values) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, httpHeaders_);
          onChanged();
        } else {
          httpHeadersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder clearHttpHeaders() {
        if (httpHeadersBuilder_ == null) {
          httpHeaders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          httpHeadersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public Builder removeHttpHeaders(int index) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.remove(index);
          onChanged();
        } else {
          httpHeadersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder getHttpHeadersBuilder(
          int index) {
        return internalGetHttpHeadersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder getHttpHeadersOrBuilder(
          int index) {
        if (httpHeadersBuilder_ == null) {
          return httpHeaders_.get(index);  } else {
          return httpHeadersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public java.util.List<? extends vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder> 
           getHttpHeadersOrBuilderList() {
        if (httpHeadersBuilder_ != null) {
          return httpHeadersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(httpHeaders_);
        }
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder addHttpHeadersBuilder() {
        return internalGetHttpHeadersFieldBuilder().addBuilder(
            vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.getDefaultInstance());
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder addHttpHeadersBuilder(
          int index) {
        return internalGetHttpHeadersFieldBuilder().addBuilder(
            index, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.getDefaultInstance());
      }
      /**
       * <pre>
       * http 请求头
       * </pre>
       *
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       */
      public java.util.List<vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder> 
           getHttpHeadersBuilderList() {
        return internalGetHttpHeadersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder> 
          internalGetHttpHeadersFieldBuilder() {
        if (httpHeadersBuilder_ == null) {
          httpHeadersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder>(
                  httpHeaders_,
                  ((bitField0_ & 0x00000040) != 0),
                  getParentForChildren(),
                  isClean());
          httpHeaders_ = null;
        }
        return httpHeadersBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes body = 8;</code>
       * @return Whether the body field is set.
       */
      @java.lang.Override
      public boolean hasBody() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes body = 8;</code>
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes body = 8;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        body_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes body = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000080);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.HttpFrame)
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.HttpFrame)
    private static final vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame();
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HttpFrame>
        PARSER = new com.google.protobuf.AbstractParser<HttpFrame>() {
      @java.lang.Override
      public HttpFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HttpFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HttpFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.HttpFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StringEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Platform.Model.StringEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code Platform.Model.StringEntry}
   */
  public static final class StringEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Platform.Model.StringEntry)
      StringEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "StringEntry");
    }
    // Use StringEntry.newBuilder() to construct.
    private StringEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StringEntry() {
      key_ = "";
      value_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_StringEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_StringEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.class, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder.class);
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>required string key = 1;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>required string value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, key_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry)) {
        return super.equals(obj);
      }
      vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry other = (vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry) obj;

      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.Model.StringEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Platform.Model.StringEntry)
        vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_StringEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_StringEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.class, vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.Builder.class);
      }

      // Construct using vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.internal_static_Platform_Model_StringEntry_descriptor;
      }

      @java.lang.Override
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry getDefaultInstanceForType() {
        return vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.getDefaultInstance();
      }

      @java.lang.Override
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry build() {
        vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry buildPartial() {
        vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry result = new vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry) {
          return mergeFrom((vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry other) {
        if (other == vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasValue()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasKey()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.StringEntry)
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.StringEntry)
    private static final vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry();
    }

    public static vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringEntry>
        PARSER = new com.google.protobuf.AbstractParser<StringEntry>() {
      @java.lang.Override
      public StringEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StringEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StringEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vip.isass.framework.net.netty.protobuf.base.NetworkFrame.StringEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_HttpFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_HttpFrame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_StringEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_StringEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022NetworkFrame.proto\022\016Platform.Model\"\306\001\n" +
      "\tHttpFrame\022\r\n\005c2sId\030\001 \001(\003\022\r\n\005s2cId\030\002 \001(\003" +
      "\022\034\n\024javaProtobufClassC2S\030\003 \001(\t\022\034\n\024javaPr" +
      "otobufClassS2C\030\004 \001(\t\022\013\n\003url\030\005 \001(\t\022\022\n\nhtt" +
      "pMethod\030\006 \001(\005\0220\n\013httpHeaders\030\007 \003(\0132\033.Pla" +
      "tform.Model.StringEntry\022\014\n\004body\030\010 \001(\014\")\n" +
      "\013StringEntry\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t" +
      "B;\n+vip.isass.framework.net.netty.protob" +
      "uf.baseB\014NetworkFrame"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Platform_Model_HttpFrame_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Platform_Model_HttpFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Platform_Model_HttpFrame_descriptor,
        new java.lang.String[] { "C2SId", "S2CId", "JavaProtobufClassC2S", "JavaProtobufClassS2C", "Url", "HttpMethod", "HttpHeaders", "Body", });
    internal_static_Platform_Model_StringEntry_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_Platform_Model_StringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Platform_Model_StringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
