<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~                    GNU LESSER GENERAL PUBLIC LICENSE
  ~                        Version 3, 29 June 2007
  ~
  ~  Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org />
  ~  Everyone is permitted to copy and distribute verbatim copies
  ~  of this license document, but changing it is not allowed.
  ~
  ~
  ~   This version of the GNU Lesser General Public License incorporates
  ~ the terms and conditions of version 3 of the GNU General Public
  ~ License, supplemented by the additional permissions listed below.
  ~
  ~   0. Additional Definitions.
  ~
  ~   As used herein, "this License" refers to version 3 of the GNU Lesser
  ~ General Public License, and the "GNU GPL" refers to version 3 of the GNU
  ~ General Public License.
  ~
  ~   "The Library" refers to a covered work governed by this License,
  ~ other than an Application or a Combined Work as defined below.
  ~
  ~   An "Application" is any work that makes use of an interface provided
  ~ by the Library, but which is not otherwise based on the Library.
  ~ Defining a subclass of a class defined by the Library is deemed a mode
  ~ of using an interface provided by the Library.
  ~
  ~   A "Combined Work" is a work produced by combining or linking an
  ~ Application with the Library.  The particular version of the Library
  ~ with which the Combined Work was made is also called the "Linked
  ~ Version".
  ~
  ~   The "Minimal Corresponding Source" for a Combined Work means the
  ~ Corresponding Source for the Combined Work, excluding any source code
  ~ for portions of the Combined Work that, considered in isolation, are
  ~ based on the Application, and not on the Linked Version.
  ~
  ~   The "Corresponding Application Code" for a Combined Work means the
  ~ object code and/or source code for the Application, including any data
  ~ and utility programs needed for reproducing the Combined Work from the
  ~ Application, but excluding the System Libraries of the Combined Work.
  ~
  ~   1. Exception to Section 3 of the GNU GPL.
  ~
  ~   You may convey a covered work under sections 3 and 4 of this License
  ~ without being bound by section 3 of the GNU GPL.
  ~
  ~   2. Conveying Modified Versions.
  ~
  ~   If you modify a copy of the Library, and, in your modifications, a
  ~ facility refers to a function or data to be supplied by an Application
  ~ that uses the facility (other than as an argument passed when the
  ~ facility is invoked), then you may convey a copy of the modified
  ~ version:
  ~
  ~    a) under this License, provided that you make a good faith effort to
  ~    ensure that, in the event an Application does not supply the
  ~    function or data, the facility still operates, and performs
  ~    whatever part of its purpose remains meaningful, or
  ~
  ~    b) under the GNU GPL, with none of the additional permissions of
  ~    this License applicable to that copy.
  ~
  ~   3. Object Code Incorporating Material from Library Header Files.
  ~
  ~   The object code form of an Application may incorporate material from
  ~ a header file that is part of the Library.  You may convey such object
  ~ code under terms of your choice, provided that, if the incorporated
  ~ material is not limited to numerical parameters, data structure
  ~ layouts and accessors, or small macros, inline functions and templates
  ~ (ten or fewer lines in length), you do both of the following:
  ~
  ~    a) Give prominent notice with each copy of the object code that the
  ~    Library is used in it and that the Library and its use are
  ~    covered by this License.
  ~
  ~    b) Accompany the object code with a copy of the GNU GPL and this license
  ~    document.
  ~
  ~   4. Combined Works.
  ~
  ~   You may convey a Combined Work under terms of your choice that,
  ~ taken together, effectively do not restrict modification of the
  ~ portions of the Library contained in the Combined Work and reverse
  ~ engineering for debugging such modifications, if you also do each of
  ~ the following:
  ~
  ~    a) Give prominent notice with each copy of the Combined Work that
  ~    the Library is used in it and that the Library and its use are
  ~    covered by this License.
  ~
  ~    b) Accompany the Combined Work with a copy of the GNU GPL and this license
  ~    document.
  ~
  ~    c) For a Combined Work that displays copyright notices during
  ~    execution, include the copyright notice for the Library among
  ~    these notices, as well as a reference directing the user to the
  ~    copies of the GNU GPL and this license document.
  ~
  ~    d) Do one of the following:
  ~
  ~        0) Convey the Minimal Corresponding Source under the terms of this
  ~        License, and the Corresponding Application Code in a form
  ~        suitable for, and under terms that permit, the user to
  ~        recombine or relink the Application with a modified version of
  ~        the Linked Version to produce a modified Combined Work, in the
  ~        manner specified by section 6 of the GNU GPL for conveying
  ~        Corresponding Source.
  ~
  ~        1) Use a suitable shared library mechanism for linking with the
  ~        Library.  A suitable mechanism is one that (a) uses at run time
  ~        a copy of the Library already present on the user's computer
  ~        system, and (b) will operate properly with a modified version
  ~        of the Library that is interface-compatible with the Linked
  ~        Version.
  ~
  ~    e) Provide Installation Information, but only if you would otherwise
  ~    be required to provide such information under section 6 of the
  ~    GNU GPL, and only to the extent that such information is
  ~    necessary to install and execute a modified version of the
  ~    Combined Work produced by recombining or relinking the
  ~    Application with a modified version of the Linked Version. (If
  ~    you use option 4d0, the Installation Information must accompany
  ~    the Minimal Corresponding Source and Corresponding Application
  ~    Code. If you use option 4d1, you must provide the Installation
  ~    Information in the manner specified by section 6 of the GNU GPL
  ~    for conveying Corresponding Source.)
  ~
  ~   5. Combined Libraries.
  ~
  ~   You may place library facilities that are a work based on the
  ~ Library side by side in a single library together with other library
  ~ facilities that are not Applications and are not covered by this
  ~ License, and convey such a combined library under terms of your
  ~ choice, if you do both of the following:
  ~
  ~    a) Accompany the combined library with a copy of the same work based
  ~    on the Library, uncombined with any other library facilities,
  ~    conveyed under the terms of this License.
  ~
  ~    b) Give prominent notice with the combined library that part of it
  ~    is a work based on the Library, and explaining where to find the
  ~    accompanying uncombined form of the same work.
  ~
  ~   6. Revised Versions of the GNU Lesser General Public License.
  ~
  ~   The Free Software Foundation may publish revised and/or new versions
  ~ of the GNU Lesser General Public License from time to time. Such new
  ~ versions will be similar in spirit to the present version, but may
  ~ differ in detail to address new problems or concerns.
  ~
  ~   Each version is given a distinguishing version number. If the
  ~ Library as you received it specifies that a certain numbered version
  ~ of the GNU Lesser General Public License "or any later version"
  ~ applies to it, you have the option of following the terms and
  ~ conditions either of that published version or of any later version
  ~ published by the Free Software Foundation. If the Library as you
  ~ received it does not specify a version number of the GNU Lesser
  ~ General Public License, you may choose any version of the GNU Lesser
  ~ General Public License ever published by the Free Software Foundation.
  ~
  ~   If the Library as you received it specifies that a proxy can decide
  ~ whether future versions of the GNU Lesser General Public License shall
  ~ apply, that proxy's public statement of acceptance of any version is
  ~ permanent authorization for you to choose that version for the
  ~ Library.
  ~
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 本项目信息 -->
    <groupId>vip.isass</groupId>
    <artifactId>isass-framework-dependencies</artifactId>
    <version>4.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <!-- region build properties -->

        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>

        <!-- endregion -->

        <!-- region isass-core -->

        <isass-framework.version>4.0.0-SNAPSHOT</isass-framework.version>

        <!-- endregion -->

        <!-- region repository -->

        <repository.releases.id>ar-releases</repository.releases.id>
        <repository.releases.name>ar-releases</repository.releases.name>
        <repository.releases.url>
            https://maven.aliyun.com/repository/public
        </repository.releases.url>

        <repository.snapshot.id>ar-snapshot</repository.snapshot.id>
        <repository.snapshot.name>ar-snapshot</repository.snapshot.name>
        <repository.snapshot.url>
            https://oss.sonatype.org/content/repositories/snapshots
        </repository.snapshot.url>

        <repository.distribution.releases.id>ar-releases</repository.distribution.releases.id>
        <repository.distribution.releases.name>ar-releases</repository.distribution.releases.name>
        <repository.distribution.releases.url>
            https://oss.sonatype.org/service/local/staging/deploy/maven2
        </repository.distribution.releases.url>

        <repository.distribution.snapshot.id>ar-snapshots</repository.distribution.snapshot.id>
        <repository.distribution.snapshot.name>ar-snapshots</repository.distribution.snapshot.name>
        <repository.distribution.snapshot.url>
            https://oss.sonatype.org/content/repositories/snapshots
        </repository.distribution.snapshot.url>

        <!-- endregion -->

        <!-- region dependencies version -->

        <!-- spring -->
        <!-- spring cloud 和 spring boot 版本关系 -->
        <!-- https://spring.io/projects/spring-cloud#overview -->

        <!-- https://spring.io/projects/spring-boot#learn -->
        <spring-boot.version>3.5.3</spring-boot.version>

        <!-- spring cloud 版本号-->
        <!-- https://spring.io/projects/spring-cloud#learn -->
        <!-- spring cloud 子项目版本号 -->
        <!--https://docs.spring.io/spring-cloud-release/reference/index.html-->
        <spring-cloud.version>2025.0.0</spring-cloud.version>

        <!--spring cloud alibaba 与 spring cloud 版本关系、以及 spring cloud alibaba 各组件版本关系-->
        <!-- https://sca.aliyun.com/docs/2023/overview/version-explain/?spm=5176.29160081.0.0.5f0478feHyXk54 -->

        <!--从2023.0.1.3和2023.0.3.2版本改了方式了遵循sping-cloud的规范了，得使用spring.cloud.config.import=xxxx来加载配置-->
        <!-- https://github.com/alibaba/spring-cloud-alibaba/issues/3952 -->
        <!-- https://github.com/alibaba/spring-cloud-alibaba/issues/3940 -->
        <!-- https://github.com/alibaba/spring-cloud-alibaba/issues/3948 -->
        <!-- https://github.com/alibaba/spring-cloud-alibaba/issues/3970 -->
        <alibaba-nacos.version>2023.0.3.3</alibaba-nacos.version>

        <jakarta.activation.version>2.1.3</jakarta.activation.version>

        <!-- apm -->
        <skywalking.version>9.2.0</skywalking.version>

        <!-- 数据库 -->
        <mybatis-plus.version>3.5.7</mybatis-plus.version>
        <!--<mybatis.version>3.5.7</mybatis.version>-->
        <flyway.version>10.15.0</flyway.version>
        <p6spy.version>3.9.1</p6spy.version>
        <dynamic-datasource.version>4.3.1</dynamic-datasource.version>
        <dameng.version>8.1.3.140</dameng.version>
        <postgresql.version>42.7.3</postgresql.version>
        <mysql.version>8.4.0</mysql.version>
        <redisson.version>3.31.0</redisson.version>
        <sqlite-jdbc.version>3.46.0.0</sqlite-jdbc.version>
        <!--<elasticsearch.version>7.2.0</elasticsearch.version>-->

        <!-- net -->
        <netty.version>4.1.111.Final</netty.version>
        <netty-socketio.version>2.0.13</netty-socketio.version>

        <!-- 序列化 -->
        <protobuf-java.version>4.31.1</protobuf-java.version>
        <protobuf-java-format.version>1.4</protobuf-java-format.version>
        <fastjson.version>2.0.57</fastjson.version>

        <!-- mq -->
        <ons.version>2.0.7.Final</ons.version>

        <!-- 工具 -->
        <hutool.version>5.8.28</hutool.version>
        <disruptor.version>4.0.0</disruptor.version>
        <guava.version>33.2.1-jre</guava.version>
        <auto-service.version>1.1.1</auto-service.version>
        <poi-ooxml.version>5.2.5</poi-ooxml.version>
        <xerces.version>2.12.2</xerces.version>
        <findbugs.version>3.0.1</findbugs.version>
        <cglib.version>3.3.0</cglib.version>
        <javassist.version>3.30.2-GA</javassist.version>

        <!-- apache-commons-->
        <commons-compress.version>1.26.2</commons-compress.version>
        <commons-io.version>2.19.0</commons-io.version>

        <!-- api接口文档 -->
        <knife4j.version>4.5.0</knife4j.version>

        <!-- 安全权限加解密 -->
        <jjwt.version>0.12.5</jjwt.version>
        <jasypt.version>3.0.5</jasypt.version>

        <!-- 工作流 -->
        <activiti.version>6.0.0</activiti.version>

        <hystrix-javanica.version>1.5.18</hystrix-javanica.version>

        <!-- 模板渲染 -->
        <freemarker.version>2.3.33</freemarker.version>

        <!-- 分布式锁 -->
        <klock.version>1.5-RELEASE</klock.version>
        <lock4j-redisson.version>2.2.7</lock4j-redisson.version>


        <!-- 金融支付 -->
        <alipay.version>4.39.109.ALL</alipay.version>

        <!-- rpc -->
        <okhttp.version>4.12.0</okhttp.version>

        <!-- 微信 -->
        <wxjava.version>4.6.2.B</wxjava.version>

        <!-- gis -->
        <geotools.version>31.1</geotools.version>
        <jts.version>1.19.0</jts.version>
        <pci.coordtransform4j.version>1.0.2</pci.coordtransform4j.version>

        <!-- 日志打印 -->
        <!-- spring-boot-dependencies 已提供版本依赖管理-->
        <!--<logback.version>1.5.18</logback.version>-->
        <!-- spring-boot-dependencies 已提供版本依赖管理-->
        <!--<jul-to-slf4j.version>2.0.17</jul-to-slf4j.version>-->
        <log4j-to-slf4j.version>2.25.0</log4j-to-slf4j.version>

        <!-- 文件管理 -->
        <xFileStorage.version>2.2.1</xFileStorage.version>
        <amazonaws-s3.version>1.12.787</amazonaws-s3.version>

        <!-- region plugins version-->

        <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>3.5.3</maven-surefire-plugin.version>
        <git-commit-id-plugin.version>4.9.10</git-commit-id-plugin.version>
        <maven-release-plugin.version>2.5.3</maven-release-plugin.version>
        <maven-assembly-plugin.version>3.7.1</maven-assembly-plugin.version>

        <!-- endregion -->
    </properties>

    <dependencies>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- spring cloud 指定spring cloud 的版本，让子项目引用 -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-dependencies</artifactId>
                <version>${knife4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>jakarta.activation</groupId>
                <artifactId>jakarta.activation-api</artifactId>
                <version>${jakarta.activation.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                <version>${alibaba-nacos.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                <version>${alibaba-nacos.version}</version>
            </dependency>

            <!-- vip.isass 系列 -->
            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-common</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-build</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-nocode-core</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-nocode-generator</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-nocode-springboot-starter</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-security-core</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-security-springsecurity</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-serialization-jackson</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-serialization-protobuf</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-database-redis</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-database-core</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-database-mysql</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-database-postgresql</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-database-dameng</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-database-mybatisplus</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-mq-core</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-mq-ons</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-mq-spring-event</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-mq-kafka011</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-net-core</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-net-netty</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-net-websocket</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-net-socketio</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-net-proxy-upstream</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-net-proxy-server</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-database-elasticsearch</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-rpc-okhttp</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-springboot-starter</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-web-springmvc</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>vip.isass</groupId>
                <artifactId>isass-framework-web-springmvc-starter</artifactId>
                <version>${isass-framework.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun.openservices</groupId>
                <artifactId>ons-client</artifactId>
                <version>${ons.version}</version>
            </dependency>

            <!-- 数据库 -->
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
            </dependency>

            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-core</artifactId>
                <version>${flyway.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
                <version>${dynamic-datasource.version}</version>
            </dependency>

            <dependency>
                <groupId>com.dameng</groupId>
                <artifactId>DmJdbcDriver18</artifactId>
                <version>${dameng.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-annotation</artifactId>
                <version>${mybatis-plus.version}</version>
                <!--<exclusions>-->
                <!--    <exclusion>-->
                <!--        <groupId>org.mybatis</groupId>-->
                <!--        <artifactId>mybatis</artifactId>-->
                <!--    </exclusion>-->
                <!--</exclusions>-->
            </dependency>

            <!--<dependency>-->
            <!--    <groupId>org.mybatis</groupId>-->
            <!--    <artifactId>mybatis</artifactId>-->
            <!--    <version>${mybatis.version}</version>-->
            <!--</dependency>-->

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-extension</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-core</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>p6spy</groupId>
                <artifactId>p6spy</artifactId>
                <version>${p6spy.version}</version>
            </dependency>

            <!-- net -->
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf-java.version}</version>
            </dependency>

            <!-- protobuf与json转换-->
            <dependency>
                <groupId>com.googlecode.protobuf-java-format</groupId>
                <artifactId>protobuf-java-format</artifactId>
                <version>${protobuf-java-format.version}</version>
            </dependency>

            <!-- netty -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty.version}</version>
            </dependency>

            <dependency>
                <groupId>com.corundumstudio.socketio</groupId>
                <artifactId>netty-socketio</artifactId>
                <version>${netty-socketio.version}</version>
            </dependency>

            <!-- 工具类 -->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.auto.service</groupId>
                <artifactId>auto-service</artifactId>
                <version>${auto-service.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <!-- activity -->
            <dependency>
                <groupId>org.activiti</groupId>
                <artifactId>activiti-spring-boot-starter-basic</artifactId>
                <version>${activiti.version}</version>
            </dependency>

            <dependency>
                <groupId>com.netflix.hystrix</groupId>
                <artifactId>hystrix-javanica</artifactId>
                <version>${hystrix-javanica.version}</version>
            </dependency>

            <dependency>
                <groupId>org.freemarker</groupId>
                <artifactId>freemarker</artifactId>
                <version>${freemarker.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.ulisesbocchio</groupId>
                <artifactId>jasypt-spring-boot-starter</artifactId>
                <version>${jasypt.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.skywalking</groupId>
                <artifactId>apm-toolkit-logback-1.x</artifactId>
                <version>${skywalking.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.skywalking</groupId>
                <artifactId>apm-toolkit-trace</artifactId>
                <version>${skywalking.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi-ooxml.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>${commons-compress.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>

            <dependency>
                <groupId>xerces</groupId>
                <artifactId>xercesImpl</artifactId>
                <version>${xerces.version}</version>
            </dependency>

            <!-- 分布式锁 -->
            <dependency>
                <groupId>cn.keking</groupId>
                <artifactId>spring-boot-klock-starter</artifactId>
                <version>${klock.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>lock4j-redisson-spring-boot-starter</artifactId>
                <version>${lock4j-redisson.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.redisson</groupId>
                        <artifactId>redisson-spring-boot-starter</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>

            <!-- alipay -->
            <dependency>
                <groupId>com.alipay.sdk</groupId>
                <artifactId>alipay-sdk-java</artifactId>
                <version>${alipay.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.code.findbugs</groupId>
                <artifactId>annotations</artifactId>
                <version>${findbugs.version}</version>
            </dependency>

            <dependency>
                <groupId>cglib</groupId>
                <artifactId>cglib</artifactId>
                <version>${cglib.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.binarywang</groupId>
                <artifactId>wx-java-spring-boot-starters</artifactId>
                <version>${wxjava.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--<dependency>-->
            <!--    <groupId>com.github.binarywang</groupId>-->
            <!--    <artifactId>weixin-java-miniapp</artifactId>-->
            <!--    <version>${wxjava.version}</version>-->
            <!--</dependency>-->

            <!--<dependency>-->
            <!--    <groupId>com.github.binarywang</groupId>-->
            <!--    <artifactId>weixin-java-pay</artifactId>-->
            <!--    <version>${wxjava.version}</version>-->
            <!--</dependency>-->

            <!--<dependency>-->
            <!--    <groupId>com.github.binarywang</groupId>-->
            <!--    <artifactId>weixin-java-open</artifactId>-->
            <!--    <version>${wxjava.version}</version>-->
            <!--</dependency>-->

            <!--<dependency>-->
            <!--    <groupId>com.github.binarywang</groupId>-->
            <!--    <artifactId>weixin-java-mp</artifactId>-->
            <!--    <version>${wxjava.version}</version>-->
            <!--</dependency>-->

            <!--<dependency>-->
            <!--    <groupId>com.github.binarywang</groupId>-->
            <!--    <artifactId>weixin-java-cp</artifactId>-->
            <!--    <version>${wxjava.version}</version>-->
            <!--</dependency>-->

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.javassist</groupId>
                <artifactId>javassist</artifactId>
                <version>${javassist.version}</version>
            </dependency>

            <dependency>
                <groupId>com.sun</groupId>
                <artifactId>tools</artifactId>
                <version>${java.version}</version>
                <scope>system</scope>
                <optional>true</optional>
                <systemPath>${env.JAVA_HOME}/lib/tools.jar</systemPath>
            </dependency>

            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-to-slf4j</artifactId>
                <version>${log4j-to-slf4j.version}</version>
            </dependency>

            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dromara.x-file-storage</groupId>
                <artifactId>x-file-storage-spring</artifactId>
                <version>${xFileStorage.version}</version>
            </dependency>

            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-s3</artifactId>
                <version>${amazonaws-s3.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                        <encoding>UTF-8</encoding>
                        <compilerArgument>-parameters</compilerArgument>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>pl.project13.maven</groupId>
                    <artifactId>git-commit-id-plugin</artifactId>
                    <version>${git-commit-id-plugin.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <prefix>git</prefix>
                        <verbose>true</verbose>
                        <dateFormat>yyyyMMddHHmmss</dateFormat>
                        <generateGitPropertiesFile>true</generateGitPropertiesFile>
                        <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
                        </generateGitPropertiesFilename>
                        <format>properties</format>
                        <abbrevLength>8</abbrevLength>
                        <failOnNoGitDirectory>false</failOnNoGitDirectory>
                        <failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>
                        <includeOnlyProperties>
                            git.build.host,git.remote.origin.url,git.build.version,git.branch,git.commit.time,git.commit.id.abbrev
                        </includeOnlyProperties>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${maven-assembly-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>bin</id>
                            <phase>package</phase>
                            <goals>
                                <goal>single</goal>
                            </goals>
                            <configuration>
                                <finalName>${project.artifactId}</finalName>
                                <descriptorRefs>
                                    <descriptorRef>assembly</descriptorRef>
                                </descriptorRefs>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>${maven-release-plugin.version}</version>
                    <configuration>
                        <tagNameFormat>@{project.version}</tagNameFormat>
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <arguments>-DskipTests</arguments>
                        <useReleaseProfile>false</useReleaseProfile>
                        <allowTimestampedSnapshots>true</allowTimestampedSnapshots>
                        <pushChanges>false</pushChanges>
                        <preparationGoals>clean validate</preparationGoals>
                        <scmCommentPrefix>chore:</scmCommentPrefix>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <developers>
        <developer>
            <name>Rain Lee</name>
            <email>lizhirong100@163.com</email>
            <organization>isass</organization>
        </developer>
    </developers>

    <repositories>
        <repository>
            <id>${repository.releases.id}</id>
            <name>${repository.releases.name}</name>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <url>${repository.releases.url}</url>
        </repository>

        <repository>
            <id>${repository.snapshot.id}</id>
            <name>${repository.snapshot.name}</name>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <url>${repository.snapshot.url}</url>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
        </repository>

        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
    </distributionManagement>
</project>